// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quixo.Api.Data;

#nullable disable

namespace Quixo.Api.Migrations
{
    [DbContext(typeof(QuixoDbContext))]
    partial class QuixoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quixo.Api.Domain.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugadorId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugadores", (string)null);
                });

            modelBuilder.Entity("Quixo.Api.Domain.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidaId"));

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoA1Id")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoA2Id")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoB1Id")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoB2Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("FechaFinalizada")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("FechaSobrescrita")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("GanadorEquipo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("GanadorSimbolo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("HistorialXml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JugadorOid")
                        .HasColumnType("int");

                    b.Property<int?>("JugadorXid")
                        .HasColumnType("int");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TableroFinalXml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartidaId");

                    b.ToTable("Partidas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
